# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
