# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_jobs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_job', to='handy.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_myjob', to='handy.User')),
            ],
        ),
    ]
