# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0003_myjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobs',
            name='description',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
    ]
