# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0006_auto_20181013_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjobs',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myjobs',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myjobs',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
