# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0008_auto_20181013_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobs',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_jobs', to='handy.User'),
        ),
    ]
