# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0009_myjobs_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjobs',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='jobs',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_jobs', to='handy.User'),
        ),
    ]
